services:
  test_db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=tests
      - POSTGRES_PASSWORD=test_admin
      - POSTGRES_DB=rusteam_test
    ports:
      - ${RUSTEAM_TEST_DB_PORT:-15432}:5432
