services:
  rusteam_db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rusteam
    ports:
      - ${RUSTEAM_DB_PORT:-5432}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rusteam-public

volumes:
  db_data:

networks:
  rusteam-public:
    name: rusteam-public
