name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo build
        env:
          TERM: xterm-256color

      - name: Run tests
        run: make test
